### ISSUE TITLE
Extending Integrations list

### ISSUE THREAD

**Issue by RinatValiullov** [bootstrap4cc/Best-Bootstrap-Awesome-List#1]
I would suggest this awesome re-implementation of the Bootstrap components using React - [React Bootstrap](https://react-bootstrap.github.io/) into the [Integrations](https://github.com/bootstrap4cc/Best-Bootstrap-Awesome-List#integrations) section

**Comment by bootstrap4cc** [comment]
thank you for your advice. I will add this into the list.
